import React, { useState } from 'react';
import '../Page.css';



function HelpPage() {
  const [selectedTile, changeTile] = useState(0);
  const [tile, setTile] = useState(0);
    return (
      <div className="help-page">
        <h1> How to Visualize </h1>
        <h2> 1 </h2>
        <p> Select an algorithm </p>
        <div className="visualizer-nav">
          <ul className="algorithms">
            <li><span> Dijkstra </span></li>
            <li><span> A* Search </span></li>
            <li><span> BFS Search </span></li>
            <li><span> DFS Search </span></li>
          </ul>
        </div>
        <h2> 2 </h2>
        <p> Select tiles using the buttons on the top left of the grid and place the tiles by pressing a grid cell </p>
        <div className="grid-options">
          <ul className="tiles">
            <li><span onClick={changeTile.bind(this, "Start")}> Start </span></li>
            <li><span onClick={changeTile.bind(this, "End")}> End </span></li>
            <li><span onClick={changeTile.bind(this, "Obstacle")}> Wall </span></li>
            <li><span onClick={changeTile.bind(this, "Empty")}> Blank </span></li>
          </ul>
          <ul className="grid-controls">
            <li><span onClick={setTile.bind(this, "Visited")}> Play </span></li>
            <li><span onClick = {tile === "Visited" ? setTile.bind(this, "Empty") : undefined}> Clear path </span></li>
            <li><span onClick={setTile.bind(this, "Empty")}> Clear grid </span></li>
          </ul>
        </div>
        <span className={tile} id="example-tile" onClick={setTile.bind(this, selectedTile)}> </span>
        <p> Use the "clear grid" button to remove all tiles and use the "clear path" button to remove the path tiles generated by the algorithms </p>
        <p> Use the play button to watch the algorithm in action </p>
      </div>
    );
}


export default HelpPage